"""Architecture-free dynamic declaration and block builders.

Use LibraryBuilder for explicit-parameter blocks. Architecture construction
is supplied separately by p4blo.arch.builder.AssemblyBuilder.
"""

from p4blo.edsl.core.blocks import (
    ACCEPT,
    REJECT,
    ActionBody,
    Block,
    Control,
    ControlBody,
    Deparser,
    DeparserBody,
    Entry,
    Key,
    Parser,
    StateBody,
    Stmts,
    Table,
    dont_care,
    entry,
    exact,
    lpm,
    masked,
    prefix,
    range_,
    ternary,
)
from p4blo.edsl.core.expr import EnumType, Errors, Expr, concat, mux
from p4blo.edsl.core.library import LibraryBuilder
from p4blo.edsl.core.types import (
    EdslError,
    ExternInstance,
    ExternType,
    HeaderType,
    StructType,
    bit,
    boolean,
    error_t,
    method,
)

__all__ = [
    "ACCEPT",
    "REJECT",
    "ActionBody",
    "Block",
    "Control",
    "ControlBody",
    "Deparser",
    "DeparserBody",
    "EdslError",
    "Entry",
    "EnumType",
    "Errors",
    "Expr",
    "ExternInstance",
    "ExternType",
    "HeaderType",
    "Key",
    "Parser",
    "LibraryBuilder",
    "StateBody",
    "Stmts",
    "StructType",
    "Table",
    "bit",
    "boolean",
    "concat",
    "dont_care",
    "entry",
    "error_t",
    "exact",
    "lpm",
    "masked",
    "method",
    "mux",
    "prefix",
    "range_",
    "ternary",
]
