# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p4blo/arch/v0/assembly.proto
# Protobuf Python Version: 7.36.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    1,
    '',
    'p4blo/arch/v0/assembly.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from p4blo.v0 import p4blo_pb2 as p4blo_dot_v0_dot_p4blo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cp4blo/arch/v0/assembly.proto\x12\rp4blo.arch.v0\x1a\x14p4blo/v0/p4blo.proto\"}\n\rBlockBindings\x12\x18\n\x07headers\x18\x01 \x01(\tR\x07headers\x12\x1a\n\x08metadata\x18\x02 \x01(\tR\x08metadata\x12/\n\x07\x65xports\x18\x03 \x03(\x0b\x32\x15.p4blo.arch.v0.ExportR\x07\x65xportsJ\x05\x08\x64\x10\xc8\x01\"9\n\x06\x45xport\x12\x12\n\x04role\x18\x01 \x01(\tR\x04role\x12\x14\n\x05\x62lock\x18\x02 \x01(\tR\x05\x62lockJ\x05\x08\x64\x10\xc8\x01\"\xf5\x03\n\rBlockAssembly\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n\x06\x65rrors\x18\x02 \x03(\tR\x06\x65rrors\x12\x37\n\x0cheader_types\x18\x03 \x03(\x0b\x32\x14.p4blo.v0.HeaderTypeR\x0bheaderTypes\x12\x37\n\x0cstruct_types\x18\x04 \x03(\x0b\x32\x14.p4blo.v0.StructTypeR\x0bstructTypes\x12\x31\n\nenum_types\x18\x05 \x03(\x0b\x32\x12.p4blo.v0.EnumTypeR\tenumTypes\x12\x37\n\x0c\x65xtern_types\x18\x06 \x03(\x0b\x32\x14.p4blo.v0.ExternTypeR\x0b\x65xternTypes\x12\x43\n\x10\x65xtern_instances\x18\x07 \x03(\x0b\x32\x18.p4blo.v0.ExternInstanceR\x0f\x65xternInstances\x12\'\n\x06\x62locks\x18\x08 \x03(\x0b\x32\x0f.p4blo.v0.BlockR\x06\x62locks\x12\x18\n\x07headers\x18\t \x01(\tR\x07headers\x12\x1a\n\x08metadata\x18\n \x01(\tR\x08metadata\x12/\n\x07\x65xports\x18\x0b \x03(\x0b\x32\x15.p4blo.arch.v0.ExportR\x07\x65xportsJ\x05\x08\x64\x10\xc8\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p4blo.arch.v0.assembly_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCKBINDINGS']._serialized_start=69
  _globals['_BLOCKBINDINGS']._serialized_end=194
  _globals['_EXPORT']._serialized_start=196
  _globals['_EXPORT']._serialized_end=253
  _globals['_BLOCKASSEMBLY']._serialized_start=256
  _globals['_BLOCKASSEMBLY']._serialized_end=757
# @@protoc_insertion_point(module_scope)
