"""The P4-SpecTec rule inventory is pinned, and the ledger's citations resolve in it.

tests/oracles/spectec-rules.json is generated by scripts/spectec-rules.py from
the pinned checkout. Two things are checked without any OCaml toolchain: the
fixture names the commit tests/oracles/build.sh pins, and every SpecTec
citation in docs/ir-semantics.md names an item the fixture has. When a
checkout built at the pin is available, the fixture is also regenerated and
compared, so a stale fixture cannot hide behind a missing toolchain in the
oracle CI job.

A citation is a backticked name on a line that starts with `SpecTec:` inside
an entry of docs/ir-semantics.md: a rule (`Stmt_eval/assignmentStatementIR`),
a relation (`Expr_eval`), a function (`$bin_satplus`) or a syntax production
(`typedExpressionIR`). Prose on that line is free; only backticked names are
checked.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[2]
FIXTURE = ROOT / "tests/oracles/spectec-rules.json"
SCRIPT = ROOT / "scripts" / "spectec-rules.py"
LEDGER = ROOT / "docs" / "ir-semantics.md"

sys.path.insert(0, str(ROOT))
from tests.oracles import run as oracle_run  # noqa: E402

CITATION_LINE = re.compile(r"^\s*(?:-\s+)?\**SpecTec:?\**:?\s*(?P<rest>.*)$")
BACKTICKED = re.compile(r"`([^`]+)`")


def load_fixture() -> dict[str, Any]:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


def pinned_commit() -> str:
    text = (ROOT / "tests/oracles/build.sh").read_text(encoding="utf-8")
    match = re.search(r"^P4_SPECTEC_COMMIT=(\w+)$", text, re.M)
    assert match, "tests/oracles/build.sh has no P4_SPECTEC_COMMIT"
    return match.group(1)


def ledger_citations() -> list[tuple[int, str]]:
    """Every backticked name on a `SpecTec:` line of the ledger, with its line."""
    citations: list[tuple[int, str]] = []
    for number, line in enumerate(LEDGER.read_text(encoding="utf-8").splitlines(), start=1):
        match = CITATION_LINE.match(line)
        if match is None:
            continue
        for name in BACKTICKED.findall(match.group("rest")):
            citations.append((number, name))
    return citations


def test_fixture_names_the_pinned_commit() -> None:
    assert load_fixture()["commit"] == pinned_commit()


def test_fixture_is_well_formed_and_sorted() -> None:
    fixture = load_fixture()
    items = fixture["items"]
    assert isinstance(items, list) and len(items) > 1000
    keys = [(i["kind"], i["name"], i["file"], i["line"]) for i in items]
    assert keys == sorted(keys), "items are not in the generator's order"
    assert "9-arch" not in {i["section"] for i in items}
    counts = fixture["counts"]
    assert set(counts) == {"dec", "relation", "rule", "rulegroup", "syntax"}
    for kind, count in counts.items():
        assert count == sum(1 for i in items if i["kind"] == kind)


def test_ledger_citations_resolve() -> None:
    names = {i["name"] for i in load_fixture()["items"]}
    unresolved = [
        f"docs/ir-semantics.md:{n}: `{name}`" for n, name in ledger_citations() if name not in names
    ]
    assert not unresolved, "SpecTec citations that name nothing at the pin:\n" + "\n".join(
        unresolved
    )


def test_fixture_matches_the_pinned_checkout() -> None:
    oracle = oracle_run.find_oracle()
    if oracle is None:
        pytest.skip("no P4-SpecTec checkout; tests/oracles/build.sh builds one")
    stamp = oracle.root / ".p4blo-built"
    if not stamp.is_file() or stamp.read_text(encoding="utf-8").split()[0] != pinned_commit():
        pytest.skip(f"{oracle.root} is not built at the pinned commit")
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--check", "--oracle-dir", str(oracle.root)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
