name = "p4blo-lean"
version = "0.1.0"
defaultTargets = ["P4bloLean"]
moreLeanArgs = ["-DwarningAsError=true"]
testDriver = "userTests"

[[require]]
name = "p4blo-ir"
path = "../ir"

[[lean_lib]]
name = "P4bloLean"

[[lean_exe]]
name = "userTests"
root = "P4bloLeanTests"
