name = "p4blo"
version = "0.1.0"
defaultTargets = ["P4blo", "UserProofAudit", "scalarExamples", "scalarCommands", "fieldExpressions", "fieldCommands", "headerReads", "callEntry"]
moreLeanArgs = ["-DwarningAsError=true"]
testDriver = "userTests"

[[require]]
name = "p4blo-ir"
path = "../ir"

[[lean_lib]]
name = "P4blo"

[[lean_exe]]
name = "userTests"
root = "P4bloTests"

[[lean_lib]]
name = "UserProofAudit"

[[lean_exe]]
name = "scalarExamples"
root = "ScalarExamplesMain"

[[lean_exe]]
name = "scalarCommands"
root = "ScalarCommandsMain"

[[lean_exe]]
name = "fieldExpressions"
root = "FieldExpressionsMain"

[[lean_exe]]
name = "fieldCommands"
root = "FieldCommandsMain"

[[lean_exe]]
name = "headerReads"
root = "HeaderReadsMain"

[[lean_exe]]
name = "callEntry"
root = "CallEntryMain"
