import P4bloArch.Assembly
import P4bloArchTest.Check
import P4bloArch.Coverage

/-!
The coverage observer of `P4bloArch.Coverage`: fixed requests report the rule
tags they must exercise, and every block traced by the observer ends where
the real entry point of `P4bloArch.Interp` ends, so the tags describe the run
the reply comes from.

The witness table, `P4bloArchTest/fixtures/witnesses.json`, pins each tag's
condition from both sides: for every tag of a closed behavior,
`<category>.<construct>.<case>`, a request that must report it and one that
must not, and for every other tag a request that must report it. Each
request also states the reply the real run gives, so a witness cannot pass
on a run that went somewhere else. The table is generated by
`witnesses.py` beside it, which says how the programs are chosen.
-/

open P4bloIR P4bloArch

namespace CoverageTests

/-- A small program with a select, a stack push past the size and a shift
past the width, as protobuf JSON. Generated once from its text form with
`p4blo.ir.dump_json` and checked by the Python validator. -/
def program : String := "{\"name\":\"coverage\",\"errors\":[\"NoError\",\"PacketTooShort\",\"NoMatch\",\"StackOutOfBounds\",\"HeaderTooShort\",\"ParserTimeout\",\"ParserInvalidArgument\"],\"header_types\":[{\"name\":\"h_t\",\"fields\":[{\"name\":\"a\",\"type\":{\"bits\":8}}]}],\"struct_types\":[{\"name\":\"H\",\"fields\":[{\"name\":\"h\",\"type\":{\"header\":\"h_t\"}},{\"name\":\"s\",\"type\":{\"stack\":{\"header\":\"h_t\",\"size\":2}}}]},{\"name\":\"M\"}],\"blocks\":[{\"name\":\"P\",\"kind\":\"BLOCK_KIND_PARSER\",\"params\":[{\"name\":\"hdr\",\"type\":{\"struct\":\"H\"},\"direction\":\"DIRECTION_OUT\"},{\"name\":\"meta\",\"type\":{\"struct\":\"M\"},\"direction\":\"DIRECTION_INOUT\"}],\"states\":[{\"name\":\"start\",\"body\":[{\"extract\":{\"target\":{\"member\":{\"base\":{\"var\":\"hdr\"},\"field\":\"h\"}}}}],\"transition\":{\"select\":{\"keys\":[{\"member\":{\"base\":{\"member\":{\"base\":{\"var\":\"hdr\"},\"field\":\"h\"}},\"field\":\"a\"}}],\"cases\":[{\"sets\":[{\"exact\":{\"bits\":{\"width\":8,\"value\":\"1\"}}}],\"target\":{\"reject\":{}}},{\"sets\":[{\"dont_care\":{}}],\"target\":{\"accept\":{}}}]}}}],\"start_state\":\"start\"},{\"name\":\"C\",\"kind\":\"BLOCK_KIND_CONTROL\",\"params\":[{\"name\":\"hdr\",\"type\":{\"struct\":\"H\"},\"direction\":\"DIRECTION_INOUT\"},{\"name\":\"meta\",\"type\":{\"struct\":\"M\"},\"direction\":\"DIRECTION_INOUT\"}],\"body\":[{\"push\":{\"stack\":{\"member\":{\"base\":{\"var\":\"hdr\"},\"field\":\"s\"}},\"count\":3}},{\"assign\":{\"target\":{\"member\":{\"base\":{\"member\":{\"base\":{\"var\":\"hdr\"},\"field\":\"h\"}},\"field\":\"a\"}},\"value\":{\"binary\":{\"op\":\"BINARY_OP_SHL\",\"left\":{\"member\":{\"base\":{\"member\":{\"base\":{\"var\":\"hdr\"},\"field\":\"h\"}},\"field\":\"a\"}},\"right\":{\"literal\":{\"bits\":{\"width\":8,\"value\":\"9\"}}}}}}}]},{\"name\":\"D\",\"kind\":\"BLOCK_KIND_DEPARSER\",\"params\":[{\"name\":\"hdr\",\"type\":{\"struct\":\"H\"},\"direction\":\"DIRECTION_IN\"}],\"body\":[{\"emit\":{\"value\":{\"member\":{\"base\":{\"var\":\"hdr\"},\"field\":\"h\"}}}},{\"emit\":{\"value\":{\"member\":{\"base\":{\"var\":\"hdr\"},\"field\":\"s\"}}}}]}],\"headers\":\"H\",\"metadata\":\"M\",\"exports\":[{\"role\":\"parser\",\"block\":\"P\"},{\"role\":\"ingress\",\"block\":\"C\"},{\"role\":\"deparser\",\"block\":\"D\"}]}"

/-- The tags one request reports, or the load error. -/
def tagsOf (p : BlockAssembly) (host : Entries) (packet : ByteArray) : Except String (List String) := do
  let index ← Index.build p
  let sw ← V1Model.load index p.toBlockBindings 4
  let externs ← P4bloArch.bind index
  pure (Coverage.run sw externs host 0 packet).sorted

/-- Whether the traced parser, control and deparser end where `runParser`,
`runControl` and `runDeparser` end on the same inputs: the same acceptance,
error, cursor and headers, then the same headers and metadata, then the same
bytes. -/
def tracesAgree (p : BlockAssembly) (host : Entries) (packet : ByteArray) : Except String Bool := do
  let index ← Index.build p
  let sw ← V1Model.load index p.toBlockBindings 4
  let externs ← P4bloArch.bind index
  let installed ← Installed.build index (some host)
  let metadata ← Value.zero (.struct sw.metadataType) index
  let parsed ← runParser index sw.parser packet metadata externs
  let some (result, run) := (Coverage.traceParser index sw.parser packet metadata externs).1
    | throw "the parser was not traced"
  let (accepted, error) := match result with
    | .ok () => (true, "NoError")
    | .error (.parse e) => (false, e)
    | .error (.interp m) => (false, m)
  let some decl := index.blocks[sw.parser]? | throw "no parser"
  let headersName := (decl.params.head?.map (·.name)).getD ""
  let parserAgrees := accepted == parsed.accepted && error == parsed.error &&
    (run.packet.map (·.cursor)) == some parsed.consumedBits &&
    run.frame.vars[headersName]? == some parsed.headers
  let (headers, metadataAfter, _) ← runControl index sw.ingress parsed.headers parsed.metadata installed externs
  let some (cResult, cRun) :=
      (Coverage.traceControl index sw.ingress parsed.headers parsed.metadata installed externs).1
    | throw "the control was not traced"
  let some cDecl := index.blocks[sw.ingress]? | throw "no control"
  let controlAgrees := match cResult, cDecl.params with
    | .ok (), [h, m] => cRun.frame.vars[h.name]? == some headers && cRun.frame.vars[m.name]? == some metadataAfter
    | _, _ => false
  let (bytes, _) ← runDeparser index sw.deparser headers externs
  let some (dResult, dRun) := (Coverage.traceDeparser index sw.deparser headers externs).1
    | throw "the deparser was not traced"
  let deparserAgrees := match dResult, dRun.emitter with
    | .ok (), some e => e.toBytes == bytes
    | _, _ => false
  pure (parserAgrees && controlAgrees && deparserAgrees)

/-- `check` that the request's tags include every one of `expected`. -/
def checkTags (name : String) (r : Except String (List String)) (expected : List String) :
    T Unit :=
  checkOk name r fun tags => expected.all tags.contains

/-- The inventory is complete and its names are unique and well formed. -/
def inventoryTests : T Unit := do
  let names := Coverage.all.map (·.name)
  check "coverage inventory names are unique" (names.eraseDups.length == names.length)
  check "coverage inventory docstrings are nonempty" (Coverage.all.all (!·.doc.isEmpty))
  check "coverage tag names round-trip"
    (Coverage.all.all fun i => i.tag.name == i.name)

/-- One row of the witness table. -/
structure Witness where
  program : String
  entries : Entries
  packet : ByteArray
  /-- Tags the request must report. -/
  hits : List String
  /-- Tags the request must not report. -/
  misses : List String
  /-- The reply `V1Model.run` gives, as `replyJson` renders it. -/
  reply : Lean.Json

/-- A witness row from its JSON object. -/
def Witness.decode (j : Lean.Json) : Except String Witness := do
  let entries ← Entries.decode "entries" (← j.getObjVal? "entries")
  pure { program := ← j.getObjValAs? String "program", entries,
         packet := ← hexToBytes? (← j.getObjValAs? String "packet"),
         hits := ← j.getObjValAs? (List String) "hits",
         misses := ← j.getObjValAs? (List String) "misses",
         reply := ← j.getObjVal? "reply" }

/-- The reply of `V1Model.run` as the witness table records it: the outputs
with the diagnostic when there is one, or the error. -/
def replyJson : Except String V1ModelResult → Lean.Json
  | .error e => Lean.Json.mkObj [("error", .str e)]
  | .ok r =>
    let outputs := r.outputs.map fun ((port, bytes) : Nat × ByteArray) =>
      Lean.Json.arr #[Lean.toJson port, .str (bytesToHex bytes)]
    Lean.Json.mkObj ([("outputs", Lean.Json.arr outputs.toArray)] ++
      (r.diagnostic.map fun d => ("diagnostic", Lean.Json.str d)).toList)

/-- The tags and the reply of one witness request, from fresh extern state. -/
def runWitness (p : BlockAssembly) (w : Witness) : Except String (List String × Lean.Json) := do
  let index ← Index.build p
  let sw ← V1Model.load index p.toBlockBindings 4
  let externs ← P4bloArch.bind index
  let tags := (Coverage.run sw externs w.entries 0 w.packet).sorted
  pure (tags, replyJson ((sw.run externs w.entries 0 w.packet).map (·.1)))

/-- Whether tag `name` stands for a closed behavior: three segments or more. -/
def closedBehavior (name : String) : Bool :=
  (name.splitOn ".").length ≥ 3

/-- The tag one segment shorter than `name`, which a negative witness of
`name` must hit when it is itself a tag, so that the negative exercises the
construct and misses only its case. -/
def parentTag (name : String) : String :=
  ".".intercalate (name.splitOn ".").dropLast

/-- What the witness table lacks: for each tag of the inventory, the missing
positive witness, the missing negative one for a closed behavior, and a
negative that does not reach the construct. -/
def witnessGaps (ws : List Witness) : List String :=
  let names := Coverage.all.map (·.name)
  names.flatMap fun n =>
    let positive := ws.any (·.hits.contains n)
    let negatives := ws.filter (·.misses.contains n)
    let parent := parentTag n
    (if positive then [] else [s!"{n}: no positive witness"]) ++
      (if closedBehavior n && negatives.isEmpty then [s!"{n}: no negative witness"] else []) ++
      (if closedBehavior n && !negatives.isEmpty && names.contains parent &&
          !negatives.any (·.hits.contains parent)
        then [s!"{n}: no negative witness hits {parent}"] else [])

/-- Every witness request reports its hits and none of its misses and gives
its recorded reply, and the table covers the inventory. -/
def witnessTests (path : System.FilePath) : T Unit := do
  let text ← IO.FS.readFile path
  let parsed : Except String (List BlockAssembly × List Witness) := do
    let j ← Lean.Json.parse text
    let programs ← (← (← j.getObjVal? "programs").getArr?).toList.mapM (BlockAssembly.decode "program")
    let witnesses ← (← (← j.getObjVal? "cases").getArr?).toList.mapM Witness.decode
    pure (programs, witnesses)
  match parsed with
  | .error e =>
    IO.println s!"     got: {e}"
    check "the witness table decodes" false
  | .ok (programs, witnesses) =>
    let names := Coverage.all.map (·.name)
    let named := witnesses.flatMap fun w => w.hits ++ w.misses
    let unknown := named.filter (!names.contains ·)
    unless unknown.isEmpty do IO.println s!"     not tags: {unknown.eraseDups}"
    check "the witness table names only tags" unknown.isEmpty
    let mut failed : List String := []
    for w in witnesses do
      let label := s!"{w.program} on {bytesToHex w.packet}"
      match programs.find? (fun (p : BlockAssembly) => p.name == w.program) with
      | none => failed := failed ++ [s!"{label}: no program"]
      | some p =>
        match runWitness p w with
        | .error e => failed := failed ++ [s!"{label}: {e}"]
        | .ok (tags, reply) =>
          if reply.compress != w.reply.compress then
            failed := failed ++ [s!"{label}: reply {reply.compress}, recorded {w.reply.compress}"]
          for t in w.hits do
            unless tags.contains t do failed := failed ++ [s!"{label}: {t} not reported"]
          for t in w.misses do
            if tags.contains t then failed := failed ++ [s!"{label}: {t} reported"]
    for f in failed do IO.println s!"     {f}"
    check s!"{witnesses.length} witness requests report their tags and replies" failed.isEmpty
    let gaps := witnessGaps witnesses
    for g in gaps do IO.println s!"     {g}"
    check "every tag has its witnesses" gaps.isEmpty

def tests (forwarder : BlockAssembly) : T Unit := do
  inventoryTests
  let bytes (l : List UInt8) : ByteArray := ⟨l.toArray⟩
  checkTags "a truncated packet hits parser.extract.tooShort"
    (tagsOf forwarder ⟨[]⟩ (bytes [0, 0])) ["parser.extract.tooShort", "stmt.extract"]
  checkTags "a whole ethernet frame takes the select default"
    (tagsOf forwarder ⟨[]⟩ (bytes (List.replicate 34 0)))
    ["parser.transition.select", "select.dontCare", "parser.target.accept"]
  checkOk "a request that cannot run reports no tags"
    (do
      let index ← Index.build forwarder
      let sw ← V1Model.load index forwarder.toBlockBindings 4
      let externs ← P4bloArch.bind index
      pure (Coverage.run sw externs ⟨[]⟩ 9 (bytes [0])).sorted)
    (·.isEmpty)
  match BlockAssembly.fromJsonString program with
  | .error e =>
    IO.println s!"     got: {e}"
    check "coverage program decodes" false
  | .ok p =>
    checkTags "a push past the size and a shift past the width"
      (tagsOf p ⟨[]⟩ (bytes [5]))
      ["stack.push.clamp", "stack.push.oversize", "expr.shl.overflow", "emit.stack",
       "emit.header.invalid", "emit.header.valid", "select.dontCare"]
    checkTags "an exact select case to reject"
      (tagsOf p ⟨[]⟩ (bytes [1])) ["select.exact", "parser.target.reject"]
    checkTags "an empty packet is too short" (tagsOf p ⟨[]⟩ ByteArray.empty)
      ["parser.extract.tooShort"]
    checkOk "a rejected parse is not a shift" (tagsOf p ⟨[]⟩ (bytes [1]))
      (!·.contains "parser.target.accept")
    -- A third parser parameter is valid core syntax, but the architecture
    -- rejects its entry binding before attempting a packet or tracing it.
    let extra : Param := { name := "extra", type := .bits 8, direction := .«in» }
    let widened := { p with blocks := p.blocks.map fun b =>
      if b.name == "P" then { b with params := b.params ++ [extra] } else b }
    checkError "v1model refuses an incompatible parser before tracing"
      (tagsOf widened ⟨[]⟩ (bytes [5])) "EXPORT_SIGNATURE"
    for packet in [bytes [5], bytes [1], ByteArray.empty] do
      checkOk s!"traced blocks agree with the entry points on {packet.size} bytes"
        (tracesAgree p ⟨[]⟩ packet) id
  for packet in [bytes [0, 0], bytes (List.replicate 34 0)] do
    checkOk s!"traced forwarder blocks agree on {packet.size} bytes"
      (tracesAgree forwarder ⟨[]⟩ packet) id

end CoverageTests
